### ISSUE TITLE
Web demo fails on Chrome Canary/Windows

### ISSUE THREAD

**Issue by MatusT** [linebender/vello#315]
Browser: Chrome Canary Version 115.0.5742.0 
OS: Windows 11

Demo on https://levien.com/vello-demo/ fails with following errors:<details>
<summary>Unrelated Errors</summary>
This first error is a result of the web server being used for the demo, and the second is not actually an error

```
with_winit_bin.js:264 `WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:
 TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
load @ with_winit_bin.js:264
with_winit_bin.js:1261 Uncaught (in promise) Error: Using exceptions for control flow, don't mind me. This isn't actually an error!
    at imports.wbg.__wbindgen_throw (with_winit_bin.js:1261:15)
    at wasm_bindgen::throw_str::h765e08dbcedb5408 (00ff85ea:0x264e7e)
    at winit::platform_impl::platform::backend::throw::h7838a6a49edb9633 (00ff85ea:0x2647e9)
    at winit::platform_impl::platform::event_loop::EventLoop<T>::run::h2d49cf311f893f48 (00ff85ea:0x25cf08)
    at winit::event_loop::EventLoop<T>::run::h7075aa75f5f8780a (00ff85ea:0x2601ba)
    at with_winit::main::{{closure}}::he82a449dac0ae17d (00ff85ea:0x78ee9)
    at wasm_bindgen_futures::task::singlethread::Task::run::h7b7188fd8c50b843 (00ff85ea:0x22e622)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h060d102d072b55f8 (00ff85ea:0x1e9a15)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hfaad5315fd80c4d2 (00ff85ea:0x261f76)
    at __wbg_adapter_58 (with_winit_bin.js:232:10)
```
</details>

```
levien.com/:1 D3D compile failed with: C:\Users\matus\AppData\Local\Google\Chrome SxS\Application\115.0.5742.0\Shader@0x000049B80022D400(90,31-71): error X3695: race condition writing to shared memory detected, consider making this write conditional.
C:\Users\matus\AppData\Local\Google\Chrome SxS\Application\115.0.5742.0\Shader@0x000049B80022D400(90,31-71): error X3695: error location reached from this location
C:\Users\matus\AppData\Local\Google\Chrome SxS\Application\115.0.5742.0\Shader@0x000049B80022D400(177,3-123): error X3695: error location reached from this location

 - While calling [Device].CreateComputePipeline([ComputePipelineDescriptor "tile_alloc"]).

levien.com/:1 D3D compile failed with: C:\Users\matus\AppData\Local\Google\Chrome SxS\Application\115.0.5742.0\Shader@0x000049B800C4C000(280,31-75): error X3695: race condition writing to shared memory detected, consider making this write conditional.
C:\Users\matus\AppData\Local\Google\Chrome SxS\Application\115.0.5742.0\Shader@0x000049B800C4C000(280,31-75): error X3695: error location reached from this location
C:\Users\matus\AppData\Local\Google\Chrome SxS\Application\115.0.5742.0\Shader@0x000049B800C4C000(659,3-129): error X3695: error location reached from this location

 - While calling [Device].CreateComputePipeline([ComputePipelineDescriptor "coarse"]).

249[Invalid ComputePipeline "tile_alloc"] is invalid.
 - While encoding [ComputePassEncoder].SetPipeline([Invalid ComputePipeline "tile_alloc"]).

249[Invalid CommandBuffer] is invalid.
    at ValidateObject (..\..\third_party\dawn\src\dawn\native\Device.cpp:689)
    at ValidateSubmit (..\..\third_party\dawn\src\dawn\native\Queue.cpp:444)

levien.com/:1 WebGPU: too many warnings, no more warnings will be reported to the console for this GPUDevice.

```

**Comment by raphlinus** [comment]
Looking at the tile_alloc failure first, as it's a lot simpler, the issue appears to be the [workgroupUniformLoad](https://github.com/linebender/vello/blob/299b47ea064ec3132e294acd9cf243eea7d9ee51/shader/tile_alloc.wgsl#L48); if that's replaced with a 0u, then the shader compiles.

This is working in Canary M115 on mac and was working on Canary on Windows at some point, though I don't have the full record.

**Comment by raphlinus** [comment]
This looks like it may be a regression in tint. I've filed https://bugs.chromium.org/p/tint/issues/detail?id=1926 to track it there.

**Comment by simbleau** [comment]
Hey there, we've updated the web demo significantly since this issue was created.

You can now visit the web demo available on
http://linebender.org/vello/ 

If you encounter problems, please file a new issue.
